### ISSUE TITLE
Error with Tibetan Unicode

### ISSUE THREAD

**Issue by ngawangtrinley** [proycon/colibri-core#37]
I'm working on a Tibetan language corpus and I get the following error message with the patternmodeller:

> Loading pattern model legya.colibri.dat as model...
> File is not a colibri model file (or a very old one)
> terminate called after throwing an instance of 'InternalError'
>   what():  Colibri internal error

The command was:

    colibri-patternmodeller -i legya.colibri.dat -t 10 -l 20 -T 3 -o legya.colibri.indexedpatternmodel

classdecode spat out the Unicode without complaining, idem for the script colibri-ngrams...

Here's the file:
[legya.txt](https://github.com/proycon/colibri-core/files/1816301/legya.txt)

**Comment by proycon** [comment]
The correct syntax  here should be ``-f legya.colibri.dat``: ``-i`` is used to read an existing pattern model. So the error message is actually correct, is trying to load something that is not a model file (but an encoded corpus).

**Comment by ngawangtrinley** [comment]
Thanks! I really should have figured this one out myself. 😳
