### ISSUE TITLE
how to expose colibri-ngrams from Python API?  

### ISSUE THREAD

**Issue by mikkokotila** [proycon/colibri-core#38]
How can I expose colibri-ngrams and the other complimentary commands through the python API?

**Comment by proycon** [comment]
Those are simple shortcut shellscripts to simplify some common tasks, they're not needed when you use the python binding. For something analogous to ``colibri-ngrams``, see https://proycon.github.io/colibri-core/doc/colibricore-python-tutorial.html under *Reading a Corpus*.

**Comment by mikkokotila** [comment]
Thanks for quick response 👍 yes I already went through the notebook. It's a great starter. So I guess the answer is that such convenience wrappers for python would have to be written (e.g. getting a frequency table of all trigrams within a corpus). Which is ok as the calls are very simple. 

I think I'll soon have some other questions (few things came up while going through the notebook side notes), but I'll finish reading the documentation first ;) 

Great work you have done. Thank you.

**Comment by mikkokotila** [comment]
Leaving this here for future generations. 

```
from collections import Counter

def gram_counts(corpusfile, classencoder, n=3):

    l = []

    corpusdata = colibricore.IndexedCorpus(corpusfile)

    for sentence in corpusdata.sentences():
        for trigram in sentence.ngrams(n):
            l.append(trigram.tostring(classdecoder))

    return Counter(l).most_common()
```

**Comment by proycon** [comment]
Thanks! :)
