### ISSUE TITLE
Problems compiling with anaconda

### ISSUE THREAD

**Issue by redadmiral** [proycon/colibri-core#43]
I had two minor issues while building from source:

1. First the installation aborted with the following error:
```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.42-b88ce.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[2]: *** [Makefile:798: SpookyV2.lo] Error 63
make[2]: Leaving directory '/home/marco/PycharmProjects/colibri-core/src'
make[1]: *** [Makefile:466: all-recursive] Error 1
make[1]: Leaving directory '/home/marco/PycharmProjects/colibri-core'
make: *** [Makefile:375: all] Error 2
Make of colibri-core failed
```
I solved this error as suggested by recreating `aclocal.m4` using `autoreconf --force --install`

2. Afterwards the compiling aborted again with the following error:
```
/home/marco/anaconda3/envs/MedInf/compiler_compat/ld: build/temp.linux-x86_64-3.7/colibricore_wrapper.o: unable to initialize decompress status for section .debug_info
build/temp.linux-x86_64-3.7/colibricore_wrapper.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```
I solved this problem with a strange workaround by giving condas `ld` another name so the system wide `ld` was used. 

I'm not sure if you are in the position to solve those problems, but I leave this here, so maybe I save others some time.

**Comment by proycon** [comment]
Thanks for the report. I think conda by default ships pretty old software when it comes to things like ld, libtool, gcc .. There's indeed not much I can do about that. I recommend our [LaMachine](https://proycon.github.io/LaMachine) distribution instead of anaconda as that includes colibri core.
